In [111]:
import csv
import pandas as pd

## Tasks for Step 1

In [112]:
# TODO: Load airports.dat.txt into a dataframe called airports_df
airports_df = pd.read_csv("airports.dat.txt", sep = ',', 
                         names =["airport_id","airport_name","city","airport_county",
                                 "faa","airport_icao","lat","lon","alt","timezone",
                                 "dst","tz"])

In [113]:
# TODO: Load airlines.dat.txt into a dataframe called airlines_df
airlines_df = pd.read_csv("airlines.dat.txt", sep = ',', 
                         names =["airline_id","airline_name","alias","iata",
                                "airline_icao","callsign","airline_county",
                                "airline_Y"])

In [114]:
# TODO: Load routes.dat.txt into a dataframe called routes_df
routes_df = pd.read_csv("routes.dat.txt", sep = ',', 
                         names =["airline_iata_icao","r_airline_id",
                                "source_airport_iata_icao",
                                 "source_airport_id",
                                 "destin_airport_iata_icao",
                                 "destin_airport_id",
                                "Y","stops","equipment"])

In [115]:
# TODO: Load On_Time_On_Time_Performance_2016_10.csv into flights_df, but
# also restrict to the following columns: 'Year','Month','DayofMonth','AirlineID','Carrier','FlightNum','Origin','Dest','ArrDelayMinutes','Cancelled'
flights_df = pd.read_csv("On_Time_On_Time_Performance_2016_10.csv", usecols =['Year','Month','DayofMonth','AirlineID','Carrier','FlightNum','Origin','Dest','ArrDelayMinutes','Cancelled'])

## Step 1.1

In [116]:
airports_df.head()

,airport_id,airport_name,city,airport_county,faa,airport_icao,lat,lon,alt,timezone,dst,tz
0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10.0,U,Pacific/Port_Moresby
1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.788700,20,10.0,U,Pacific/Port_Moresby
2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10.0,U,Pacific/Port_Moresby
3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10.0,U,Pacific/Port_Moresby
4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.220050,146,10.0,U,Pacific/Port_Moresby

In [117]:
# Output airlines_df
airlines_df.head()

,airline_id,airline_name,alias,iata,airline_icao,callsign,airline_county,airline_Y
0,1,Private flight,\N,-,NaN,NaN,NaN,Y
1,2,135 Airways,\N,NaN,GNL,GENERAL,United States,N
2,3,1Time Airline,\N,1T,RNX,NEXTIME,South Africa,Y
3,4,2 Sqn No 1 Elementary Flying Training School,\N,NaN,WYT,NaN,United Kingdom,N
4,5,213 Flight Unit,\N,NaN,TFU,NaN,Russia,N

In [118]:
# Output routes_df
routes_df.head()

,airline_iata_icao,r_airline_id,source_airport_iata_icao,source_airport_id,destin_airport_iata_icao,destin_airport_id,Y,stops,equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2

In [119]:
# Output flights_df
flights_df.head()

,Year,Month,DayofMonth,AirlineID,Carrier,FlightNum,Origin,Dest,ArrDelayMinutes,Cancelled
0,2016,10,3,19805,AA,1,BOS,JFK,0.0,0.0
1,2016,10,4,19805,AA,1,BOS,JFK,0.0,0.0
2,2016,10,1,19805,AA,1,JFK,LAX,0.0,0.0
3,2016,10,2,19805,AA,1,JFK,LAX,18.0,0.0
4,2016,10,3,19805,AA,1,JFK,LAX,0.0,0.0

## Step 1.2

In [120]:
from bs4 import BeautifulSoup

input_html = "aircraft_incidents.htm"
with open(input_html, "r") as ifile:
    soup = BeautifulSoup(ifile, 'html5lib')

In [121]:
# TODO: Select Year and Incident description. 
# It can be seen that they are usually <h3> or <li> tags.
selected_data = ""
for text in soup.find_all(['h3','li']):
    selected_data = selected_data + text.text + '/n' 
# Assign the results to variable selected_data
selected_data[:5]

'1919['

In [122]:
# TODO: Check if all tags have been removed
emlist = []
def checktags(tag_item):
    if ('<' or '>') in tag_item:
        emist.append[tag_item] 
    
selected_data_list = selected_data.split('/n')
for i in selected_data_list:
    checktags(i)
if len(emlist) ==0:
    print("No Tag Found!")
# Output 'No Tag Found!' if no tags

No Tag Found!

In [123]:
# TODO: Output selected_data
selected_data[:10]

'1919[edit]'

In [124]:
# TODO: Write selected_data to incidents_raw.txt
with open("incidents_raw.txt","w") as f:
        f.write(selected_data)

## Tasks for Step 2

(use Insert|Insert Cell Above or Insert Cell Below as needed to add further cells)

In [125]:
# fillna

# Replace NaNs with blanks if the column is a string, so we don’t get
# objects in the column
def fillna_col(series):
    if series.dtype is pd.np.dtype(object):
        return series.fillna('')
    else:
        return series

In [126]:
# TODO: Define nullify here

# Replace \Ns with NaNs
def nullify(x):
    if x == "\\N":
        return float('NaN')  # TODO: replace this!
    else:
        return x

In [127]:
# TODO: regularize and remove nulls according to Step 2
def clean(df):
    return df.applymap(nullify).apply(fillna_col)
airports_df = clean(airports_df)
airlines_df = clean(airlines_df)
flights_df = clean(flights_df)
routes_df = routes_df.applymap(nullify)
routes_df = routes_df.dropna(axis=0, how='any', subset=['r_airline_id', 'source_airport_id', 'destin_airport_id'])
routes_df = routes_df.apply(fillna_col)

airlines_df

,airline_id,airline_name,alias,iata,airline_icao,callsign,airline_county,airline_Y
0,1,Private flight,,-,,,,Y
1,2,135 Airways,,,GNL,GENERAL,United States,N
2,3,1Time Airline,,1T,RNX,NEXTIME,South Africa,Y
3,4,2 Sqn No 1 Elementary Flying Training School,,,WYT,,United Kingdom,N
4,5,213 Flight Unit,,,TFU,,Russia,N
5,6,223 Flight Unit State Airline,,,CHD,CHKALOVSK-AVIA,Russia,N
6,7,224th Flight Unit,,,TTF,CARGO UNIT,Russia,N
7,8,247 Jet Ltd,,,TWF,CLOUD RUNNER,United Kingdom,N
8,9,3D Aviation,,,SEC,SECUREX,United States,N
9,10,40-Mile Air,,Q5,MLA,MILE-AIR,United States,Y
10,11,4D Air,,,QRT,QUARTET,Thailand,N
11,12,611897 Alberta Limited,,,THD,DONUT,Canada,N
12,13,Ansett Australia,,AN,AAA,ANSETT,Australia,Y
13,14,Abacus International,,1B,,,Singapore,Y
14,15,Abelag Aviation,,W9,AAB,ABG,Belgium,N
15,16,Army Air Corps,,,AAC,ARMYAIR,United Kingdom,N
16,17,Aero Aviation Centre Ltd.,,,AAD,SUNRISE,Canada,N
17,18,Aero Servicios Ejecutivos Internacionales,,,SII,ASEISA,Mexico,N
18,19,Aero Biniza,,,BZS,BINIZA,Mexico,N
19,20,Aero Albatros,,,ABM,ALBATROS ESPANA,Spain,N
20,21,Aigle Azur,,ZI,AAF,AIGLE AZUR,France,Y
21,22,Aloha Airlines,,AQ,AAH,ALOHA,United States,Y
22,23,Alaska Island Air,,,AAK,ALASKA ISLAND,United States,N
23,24,American Airlines,,AA,AAL,AMERICAN,United States,Y
24,25,Aviation Management Corporation,,,AAM,AM CORP,United States,N
25,26,Atlantis Airlines (USA),,,AAO,ATLANTIS AIR,United States,N
26,27,Aerovista Airlines,,,AAP,AEROVISTA GROUP,United Arab Emirates,N
27,28,Asiana Airlines,,OZ,AAR,ASIANA,Republic of Korea,Y
28,29,Askari Aviation,,4K,AAS,AL-AAS,Pakistan,Y
29,30,Australia Asia Airlines,,,AAU,AUSTASIA,Australia,N
...,...,...,...,...,...,...,...,...
6018,19651,CARICOM AIRWAYS (BARBADOS) INC.,CARICOM AIRWAYS,,CCB,,Barbados,Y
6019,19674,Rainbow Air (RAI),Rainbow Air (RAI),RN,RAB,Rainbow,United States,Y
6020,19675,Rainbow Air Canada,Rainbow Air CAN,RY,RAY,Rainbow CAN,Canada,Y
6021,19676,Rainbow Air Polynesia,Rainbow Air POL,RX,RPO,Rainbow Air,United States,Y
6022,19677,Rainbow Air Euro,Rainbow Air EU,RU,RUE,Rainbow Air,United Kingdom,Y
6023,19678,Rainbow Air US,Rainbow Air US,RM,RNY,Rainbow Air,United States,Y
6024,19745,Transilvania,,,TNS,,Romania,Y
6025,19751,Dobrolet,Добролёт,QD,DOB,DOBROLET,Russia,Y
6026,19774,Spike Airlines,Aero Spike,S0,SAL,Spike Air,United States,Y
6027,19776,Grand Cru Airlines,,,GCA,,Lithuania,Y
6028,19785,Go2Sky,,,RLX,RELAX,Slovakia,Y
6029,19803,All Argentina,All Argentina,L1,AL1,,Argentina,Y
6030,19804,All America,All America,A2,AL2,,United States,Y
6031,19805,All Asia,All Asia,L9,AL3,,China,Y
6032,19806,All Africa,All Africa,9A,99F,,South Africa,Y
6033,19807,Regionalia México,Regionalia México,N4,J88,,Mexico,Y
6034,19808,All Europe,All Europe,N9,N99,,United Kingdom,Y
6035,19809,All Spain,All Spain,N7,N77,,Spain,Y
6036,19810,Regional Air Iceland,Regional Air Iceland,9N,N78,,Iceland,Y
6037,19811,British Air Ferries,,??,??!,,United Kingdom,N
6038,19812,Voestar,Voestar Brasil,8K,K88,,Brazil,Y
6039,19813,All Colombia,All Colombia,7O,7KK,,Colombia,Y
6040,19814,Regionalia Uruguay,Regionalia Uruguay,2X,2K2,,Uruguay,Y
6041,19815,Regionalia Venezuela,Regionalia Venezuela,9X,9XX,,Venezuela,Y
6042,19827,Regionalia Chile,Regionalia Chile,9J,CR1,,Chile,Y
6043,19828,Vuela Cuba,Vuela Cuba,6C,6CC,,Cuba,Y
6044,19830,All Australia,All Australia,88,8K8,,Australia,Y
6045,19831,Fly Europa,,ER,RWW,,Spain,Y
6046,19834,FlyPortugal,,PO,FPT,FlyPortugal,Portugal,Y
6047,19845,FTI Fluggesellschaft,,,FTI,,Germany,N

In [128]:
# TODO: change column types according to Step 2
routes_df['r_airline_id'] = routes_df['r_airline_id'].astype(int)
routes_df['source_airport_id'] = routes_df['source_airport_id'].astype(int)
routes_df['destin_airport_id'] = routes_df['destin_airport_id'].astype(int)

In [129]:
# TODO: read and clean raw text file and store in clean_incidents
with open("incidents_raw.txt","r") as incident:
    read_incident = incident.read()
    replace_incident = read_incident.replace("[edit]", "")
    list_incident = replace_incident.split("/n")

ind = list_incident.index("1997")
list_incident = list_incident[ind:]

new_list =[]
for i in list_incident:
    if len(i) == 4:
        flag = i
    else:
        new_list.append(flag + " " +i)

clean_list = []
for i in new_list:
    if "flight" or "-" in new_list:
        print(i)
        clean_list.append(i)

1997 January 9 – Comair Flight 3272, an Embraer EMB 120 Brasília, crashes near Ida, Michigan, during a snowstorm, killing all 29 on board.
1997 March 18 – Stavropolskaya Aktsionernaya Avia Flight 1023, an Antonov An-24, breaks up in flight and crashes near Cherkessk, Russia; all 50 on board die.
1997 April 19 – Merpati Nusantara Airlines Flight 106, a BAe ATP crashes during a failed go-around in bad weather at Buluh Tumbang International Airport, Indonesia. 15 of the 53 passengers and crew are killed.
1997 May 8 – China Southern Airlines Flight 3456, a Boeing 737, makes a hard landing in Shenzhen, China, during poor weather and crashes, killing 35 of the 74 people on board.
1997 July 31 – FedEx Express Flight 14, a McDonnell Douglas MD-11, crashes upon landing at Newark Liberty International Airport; the two crew members and three passengers escape uninjured.
1997 July 17 – Sempati Air Flight 304, a Fokker F27, crashes shortly after take off from Husein Sastranegara International Airport. 28 people were killed.
1997 August 6 – Korean Air Flight 801, a Boeing 747, crashes while attempting to land in heavy rain at Guam International Airport; of the 254 people on board, only 26 survive.
1997 August 10 – Formosa Airlines Flight 7601, a Dornier Do 228, crashes while attempting to land at Beigan, Lienchiang, in the Matsu Islands. All 16 passengers and crew on board are killed.
1997 September 3 – Vietnam Airlines Flight 815, a Tupolev Tu-134, crashes on approach to Phnom Penh International Airport in heavy rain, killing 64 of the 66 people on board.
1997 September 6 – Royal Brunei Airlines Flight 238, a Dornier Do 228, crashes into a hill side in Lambir Hills National Park, killing all 10 on board.
1997 September 26 – Garuda Indonesia Flight 152, an Airbus A300, crashes into a mountain near Buah Nabar, Indonesia, killing all 234 on board.
1997 October 10 – Austral Líneas Aéreas Flight 2553, a McDonnell Douglas DC-9, crashes near Fray Bentos, Uruguay, traveling from Posadas to Buenos Aires, resulting in the death of all 74 occupants.
1997 December 15 – Tajikistan Airlines Flight 3183, a Tupolev Tu-154, crashes into the desert near Sharjah Airport, of the 86 on board, only the flight engineer survives.
1997 December 17 – Aerosvit Flight 241, a Yakovlev Yak-42, crashes near Thessaloniki, Greece, killing all 70 people on board.
1997 December 19 – SilkAir Flight 185, a Boeing 737, crashes into the Musi River near Palembang, Indonesia, killing all 102 people on board.
1997 December 28 – United Airlines Flight 826, a Boeing 747, encounters severe turbulence two hours into the flight; the aircraft safely lands back in Tokyo; all survive the accident, but a passenger dies later; despite having no damage, the aircraft is written off.
1998 February 2 – Cebu Pacific Flight 387, a McDonnell Douglas DC-9, crashes into a mountain near Mount Sumagaya in Misamis Oriental in the Philippines, killing all 104 passengers and crew members on board.
1998 February 16 – China Airlines Flight 676, an Airbus A300, crashes into a residential area while attempting to land in Taipei, Taiwan. All 196 people on board are killed, in addition to six on the ground.
1998 March 19 – In the 1998 Ariana Afghan Airlines crash, a Boeing 727 crashes into Sharki Baratayi Mountain while on approach to Kabul International Airport, killing all 45 on board.
1998 March 22 – Philippine Airlines Flight 137, an Airbus A320, overshoots the end of the runway while landing at Bacolod City in the Philippines, plowing through several houses. None of the passengers was harmed, but three people on the ground are killed and several more injured.
1998 April 20 – Air France Flight 422, a Boeing 727 leased from TAME Airlines, crashes into the mountains east of Bogotá, Colombia, on takeoff from El Dorado International Airport of Bogotá in foggy weather. All 53 passengers and crew perish.
1998 May 5 – In the 1998 Occidental Petroleum Boeing 737 crash, a Boeing 737 leased from the Peruvian Air Force crashes while on approach to Alférez FAP Alfredo Vladimir Sara Bauer Airport, killing 75 of 88 on board.
1998 May 25 – PIA Flight 544, a Fokker F-27, is hijacked shortly after takeoff by three armed men. F-16 fighter jets intercept the plane and force it to land. The hijackers are arrested and sentenced to death. All 38 on board survive.
1998 May 26 – The 1998 MIAT Mongolian Airlines crash: a Harbin Y-12 crashes 13 minutes after takeoff from Erdenet Airport, Mongolia, killing all 28 passengers and crew.
1998 June 18 – Propair Flight 420, a Fairchild Metroliner crashes shortly after takeoff from Dorval Airport (now Montréal–Pierre Elliott Trudeau International Airport), Canada following an inflight fire. All 11 passengers and crew are killed.
1998 July 30 – Proteus Airlines Flight 706: a Beechcraft 1900D collides in mid-air with a light aircraft over Quiberon Bay. Both aircraft crash into the sea, killing 15 people.
1998 August 24 – Myanma Airways Flight 635, a Fokker F-27 Friendship, crashes while on approach to Tachilek Airport; all 36 on board die.
1998 August 29 – Cubana de Aviación Flight 389, a Tupolev Tu-154M overruns the runway whilst taking off from Quito's Mariscal Sucre International Airport, Ecuador, proceeding to crash into a soccer field. 70 of the 91 passengers and crew are killed, along with 10 on the ground.
1998 September 2 – Swissair Flight 111, a McDonnell Douglas MD-11, crashes into the sea near Halifax, Nova Scotia in Canada, because of an onboard fire. All 229 people on board perish.
1998 September 25 – PauknAir Flight 4101, a BAe 146, leaves Málaga but never reaches its destination in Melilla. All passengers and crew perish.
1998 September 29 – Lionair Flight 602, an Antonov An-24, is shot down by the Liberation Tigers of Tamil Eelam and crashes off the coast of Jaffna, Sri Lanka, killing all 55 on board.
1998 October 10 – The 1998 Lignes Aériennes Congolaises crash occurs when rebels using a Strela 2 missile shoot down the Boeing 727, which crashes near Kindu, Democratic Republic of Congo, killing all 41 on board.
1998 December 11 – Thai Airways International Flight 261, an Airbus A310, crashes during poor weather near Surat Thani, Thailand. Of the 146 people on board, 102 are killed.
1999 February 24 – China Southwest Airlines Flight 4509, a Tupolev Tu-154, crashes while on approach to Wenzhou Airport, killing all 61 passengers and crew on board.
1999 April 7 – Turkish Airlines Flight 5904, a Boeing 737-400, crashes in poor weather near Hamdilli, Ceyhan, Turkey; all six crew die.
1999 April 15 – Korean Air Cargo Flight 6316, a McDonnell Douglas MD-11F crashes shortly after takeoff from Shanghai Hongqiao Airport, China. All three crew members, as well as five on the ground, are killed.
1999 June 1 – American Airlines Flight 1420, a McDonnell Douglas MD-82 with 139 passengers on board, skids off the runway on landing and crashes into a steel walkway at Little Rock, Arkansas during strong winds; 11 are killed, and 86 are injured.
1999 July 24 – Air Fiji Flight 121, an Embraer EMB 110 Bandeirante crashes into a mountain en route to Nadi International Airport, Fiji. All 17 passengers and crew are killed.
1999 July 24 – All Nippon Airways Flight 61, a Boeing 747, is hijacked by a passenger, Yuji Nishizawa, wielding a knife; after fatally stabbing the captain, he is overpowered by the crew; the first officer lands the plane safely at Haneda, Japan.
1999 August 7 – TACV Flight 5002, a Dornier Do 228 crashes into a mountain whilst returning to São Pedro Airport, Cape Verde in poor weather. All 18 passengers and crew are killed.
1999 August 22 – China Airlines Flight 642, a McDonnell Douglas MD-11, crashes on landing at Hong Kong International Airport during "Typhoon" Sam; of the 315 people on board, three die.
1999 August 31 – LAPA Flight 3142, a Boeing 737, overshoots the runway in Buenos Aires, Argentina, and crashes into a golf course; of the 103 people on board, 63 are killed, as well as two on the ground.
1999 September 5 – Necon Air Flight 128, a BAe 748 collides with a telecommunications tower whilst on approach into Kathmandu Airport, Nepal. All 15 passengers and crew are killed.
1999 September 14 – Britannia Airways Flight 226A, a Boeing 757, veers off the runway at Girona, Catalonia Spain, while landing in a thunderstorm and comes to rest in a field, broken apart in two places; 43 on board are injured, two seriously, but a passenger initially diagnosed as "lightly injured" dies five days later of unnoticed internal injuries.
1999 September 23 – Qantas Flight 1, a Boeing 747 runs off the runway due to a storm and comes to a complete stop just short of a golf course. All on board including 30 injured passengers survive.
1999 October 31 – EgyptAir Flight 990, a Boeing 767 bound for Cairo, Egypt, crashes into the Atlantic Ocean off Nantucket, Massachusetts, killing all 217 passengers and crew; cause is disputed: a deliberate suicide/homicide act by the relief first officer according to the NTSB, vs. a Boeing mechanical flaw according to Egyptian aviation authorities.
1999 November 9 – TAESA Flight 725, a McDonnell Douglas DC-9, crashes near Uruapan, Mexico, killing all 18 on board.
1999 November 12 – Si Fly Flight 3275, an ATR 42-300 operating a UN relief flight strikes a mountain in poor weather whilst on approach into Pristina Airport, Kosovo. All 24 passengers and crew are killed.
1999 December 7 – Asian Spirit Flight 100, a Let L-410 Turbolet, crashes into a mountain while on approach to Cauayan Airport, killing all 15 passengers and crew on board.
1999 December 11 – SATA Air Açores Flight 530M, a BAe ATP crashes into a mountain whilst on approach into Flores Airport in the Azores. All 35 passengers and crew are killed.
1999 December 21 – Cubana de Aviación Flight 1216, a McDonnell Douglas DC-10, overruns the runway at La Aurora International Airport, killing 16 of 314 people on board and another two on the ground.
1999 December 22 – Korean Air Cargo Flight 8509, a Boeing 747-200F, crashes after takeoff near Great Hallingbury, England; killing all four crew.
1999 December 24 – Indian Airlines Flight 814, an Airbus A300, is hijacked en route to Delhi, India; one hostage is killed.
1999 December 25 – Cubana de Aviación Flight 310, a Yakovlev Yak-42D, crashes into the San Luis Hill near Bejuma, Venezuela, while on approach to Arturo Michelena International Airport; all 22 on board die.
2000 January 10 – Crossair Flight 498, a Saab 340, crashes two minutes after takeoff in Niederhasli, Switzerland, killing all 10 people on board.
2000 January 13 – In the 2000 Marsa Brega Short 360 crash, a Short 360 ditches into the sea near Marsa Brega, Libya as a result of ice buildup. 22 of the 41 passengers and crew are killed.
2000 January 30 – Kenya Airways Flight 431, an Airbus A310, carrying 169 passengers and 10 crew members, crashes into the Atlantic Ocean off Côte d'Ivoire after takeoff from Abidjan. Only 10 people survive.
2000 January 31 – Alaska Airlines Flight 261, an MD-83, crashes into the Pacific Ocean off Point Mugu, California, after problems with its horizontal stabilizer. All 83 passengers and five crew members are killed.
2000 February 16 – Emery Worldwide Flight 17, a DC-8-71F crashes into a salvage yard shortly after takeoff from Sacramento Mather Airport, California. All three crew members are killed.
2000 March 5 – Southwest Airlines Flight 1455, a Boeing 737-300, overruns the runway in Burbank, California. Of the 142 people on board, 43 are injured, two seriously.
2000 April 19 – Air Philippines Flight 541, a Boeing 737-200, crashes in a coconut plantation on Samal Island, Davao del Norte while preparing to approach the Davao International Airport, killing all 131 people on board in the worst ever accident involving the 737-200.
2000 June 22 – Wuhan Airlines Flight 343, a Xian Y-7, is struck by lightning and crashes in Hanyang District, Wuhan, killing all 42 on board and another seven on the ground in the worst ever accident involving the Y-7.
2000 July 4 – Malév Flight 262, a Tupolev Tu-154, lands on its belly at Thessaloniki International Airport in Greece. There are no serious injuries or fatalities.
2000 July 8 – Aerocaribe Flight 7831, a British Aerospace Jetstream 32, crashes near Chulum Juárez, Mexico, killing all 19 on board.
2000 July 12 – Hapag-Lloyd Flight 3378, an Airbus A310, crash-lands 650 metres short of the runway in Vienna after running out of fuel in flight. There are no serious injuries or fatalities.
2000 July 17 – Alliance Air Flight 7412, a Boeing 737-200, crashes into government housing in Patna, India, as it approaches the airport, killing 55 of the 58 on board and five people on the ground.
2000 July 25 – Air France Flight 4590, a Concorde crashes during takeoff from Paris, France, after striking debris on the runway, killing all 100 passengers and nine crew aboard as well as four on the ground; the entire Concorde fleet is grounded for one year.
2000 August 23 – Gulf Air Flight 072, an Airbus A320, crashes into the Persian Gulf off Manama, Bahrain, while attempting to land. All 135 passengers and eight crew members are killed.
2000 October 31 – Singapore Airlines Flight 006, a Boeing 747-400, strikes construction equipment after using a closed runway for takeoff at Chiang Kai-shek International Airport, Taiwan, killing 83 out of 179 people on board.
2000 November 15 – In the 2000 ASA Pesada Antonov An-24 crash, an Antonov An-24 suffers a catastrophic engine failure and crashes shortly after takeoff from Luanda's Quatro de Fevereiro International Airport, Angola. All 57 passengers and crew are killed.
2000 November 18 – Dirgantara Air Service Flight 3130, a Britten Norman Islander BN-2 crashes shortly after take off from Datah Dawai Airport in East Kalimantan, Indonesia. No one is killed, but all on board were injured, 11 seriously.
2000 December 20 – British Airways Flight 2069, in Sudanese airspace at 35,000 ft, a hijacker storms the cabin in an attempt to send the plane into a nosedive. However, Captain William Hagan and First Officer Richard Webb help subdue the mentally ill hijacker, while First Officer Phil Watson levels the flight. None of the 398 on board is seriously injured.
2001 January 23 – Yemenia Flight 448, a Boeing 727, is hijacked 15 minutes after takeoff from Sana'a International Airport, Yemen; the crew makes an emergency landing at Djibouti; the hijacker is subdued with no casualties to the 101 on board.
2001 January 25 – RUTACA Airlines Flight 225, a Douglas DC-3 crashes shortly after takeoff from Tomás de Heres Airport, Venezuela as a result of an engine failure. All 24 passengers and crew were killed.
2001 January 31 – In the 2001 Japan Airlines mid-air incident, Japan Airlines Flight 907, a Douglas DC-10, and Japan Airlines Flight 958, a Boeing 747, narrowly avoid colliding by a margin of 36 feet (11 meters) near Yaizu, Japan.
2001 February 27 – Loganair Flight 670A, a Short 360 operating a postal flight crashes shortly after takeoff from Edinburgh Airport, Scotland as a result of a double engine failure. Both crew members are killed.
2001 March 3 – Thai Airways International Flight 114, a Boeing 737-400 is destroyed by an explosion while on the tarmac at Don Mueang Airport, Thailand. One flight attendant is killed in the explosion, which happened prior to boarding.
2001 March 24 – Air Caraïbes Flight 1501, a DHC-6 Twin Otter crashes into a house whilst on approach into Saint Barthélemy Airport, Guadeloupe. All 19 passengers and crew, as well as one person on the ground, are killed.
2001 March 29 – In the 2001 Avjet Aspen crash, an Avjet charter flight, a Gulfstream III jet with 15 passengers and three crew, crashes on approach into Aspen, Colorado, killing all on board.
2001 July 4 – Vladivostok Air Flight 352, a Tupolev Tu-154 enters a flat spin on approach to Irkutsk Airport in Irkutsk, Russia, crashes down onto its belly and bursts into flames in a wooded area, killing all 145 aboard.
2001 August 24 – Air Transat Flight 236, an Airbus A330, runs out of fuel over the Atlantic Ocean and makes an emergency landing in the Azores. Upon landing some of the tires blow out, causing a fire that is extinguished by emergency personnel on the ground. None of the 304 people on board the aircraft is seriously injured.
2001 August 29 – Binter Mediterráneo Flight 8261, a CASA CN-235, suffers port engine failure and crashes onto the N-340 road while attempting to make an emergency landing at Ruiz Picasso International Airport, killing four of 43 on board; the pilot initially survives, but dies several hours later.
2001 September 11 attacks

September 11 – American Airlines Flight 11, a Boeing 767-200ER with 92 people on board, is hijacked after taking off from Boston, and is flown into the north tower of the World Trade Center in New York City; all on board are killed as well as around 1600 people on the ground and in the building; the collapse of both towers brings the total death toll from the two crashes to at least 2,763, the worst disaster involving commercial aircraft.
September 11 – United Airlines Flight 175, a Boeing 767-200 with 65 people on board, is hijacked after taking off from Boston and is flown into the south tower of the World Trade Center in New York City; all on board are killed as well as around 900 people on the ground and in the building; the collapse of both towers brings the total death toll from the two crashes to at least 2,763, the worst disaster involving commercial aircraft.
September 11 – American Airlines Flight 77, a Boeing 757-200 with 64 people on board, is hijacked after taking off from Dulles International Airport and is flown into The Pentagon; all on board are killed as well as 125 people in the building and on the ground.
September 11 – United Airlines Flight 93, a Boeing 757-200 with 44 people on board, is hijacked after taking off from Newark, New Jersey; passengers struggle with the hijackers, and the aircraft crashes in a field near Shanksville, Pennsylvania, killing all on board.


2001 September 11 – American Airlines Flight 11, a Boeing 767-200ER with 92 people on board, is hijacked after taking off from Boston, and is flown into the north tower of the World Trade Center in New York City; all on board are killed as well as around 1600 people on the ground and in the building; the collapse of both towers brings the total death toll from the two crashes to at least 2,763, the worst disaster involving commercial aircraft.
2001 September 11 – United Airlines Flight 175, a Boeing 767-200 with 65 people on board, is hijacked after taking off from Boston and is flown into the south tower of the World Trade Center in New York City; all on board are killed as well as around 900 people on the ground and in the building; the collapse of both towers brings the total death toll from the two crashes to at least 2,763, the worst disaster involving commercial aircraft.
2001 September 11 – American Airlines Flight 77, a Boeing 757-200 with 64 people on board, is hijacked after taking off from Dulles International Airport and is flown into The Pentagon; all on board are killed as well as 125 people in the building and on the ground.
2001 September 11 – United Airlines Flight 93, a Boeing 757-200 with 44 people on board, is hijacked after taking off from Newark, New Jersey; passengers struggle with the hijackers, and the aircraft crashes in a field near Shanksville, Pennsylvania, killing all on board.
2001 October 4 – Siberia Airlines Flight 1812, a Tupolev Tu-154, is shot down by the Ukrainian military over the Black Sea. All 66 passengers and 12 crew members are killed.

In [130]:
# TODO: convert clean_incidents into dataframe incidents_df
incidents_df = pd.DataFrame(columns=['Date', 'Airline', 'FlightNum'])

import re
year =[]
month =[]
date =[]
airl =[]
fli_n = []
dict_month = {'January':'1', 'February':'2','March':'3','April':'4','May':'5', 'June':'6','July':'7','August':'8',
              'September':'9','October':'10','November':'11','December':'12'}
for i in clean_list:
    m = re.search('(\d{4})\s(\w+)\s(\d{1,2})\s[–].*?\s([^,:]+)\sFlight\s(\d+)\W', i)
    if m:
        n = m.group(1)
        a = m.group(2)
        b = m.group(3)
        c = m.group(4)
        d = m.group(5)
        year.append(n)
        month.append(a)
        date.append(b)
        airl.append(c)
        fli_n.append(d)
month_new = []        
for i in month:
    month_new.append(dict_month.get(i))

time = []
for i in range(len(year)):
    j = year[i]+'-'+month[i]+'-'+date[i]
    time.append(j)

s_time = pd.Series(time)
s_airl = pd.Series(airl)
s_fli_n = pd.Series(fli_n)
incidents_df['Date'] = s_time.values
incidents_df['Airline'] = s_airl.values
incidents_df['FlightNum'] = s_fli_n.values
incidents_df.drop_duplicates() 
print(len(incidents_df))

317

In [131]:
# TODO: change column type of 'Date'
incidents_df['Date'] = pd.to_datetime(incidents_df['Date'])
print(incidents_df.head(100))

         Date                            Airline FlightNum
0  1997-01-09                             Comair      3272
1  1997-03-18  Stavropolskaya Aktsionernaya Avia      1023
2  1997-04-19         Merpati Nusantara Airlines       106
3  1997-05-08            China Southern Airlines      3456
4  1997-07-31                      FedEx Express        14
5  1997-07-17                        Sempati Air       304
6  1997-08-06                         Korean Air       801
7  1997-08-10                   Formosa Airlines      7601
8  1997-09-03                   Vietnam Airlines       815
9  1997-09-06              Royal Brunei Airlines       238
10 1997-09-26                   Garuda Indonesia       152
11 1997-10-10              Austral Líneas Aéreas      2553
12 1997-12-15                Tajikistan Airlines      3183
13 1997-12-17                           Aerosvit       241
14 1997-12-19                            SilkAir       185
15 1997-12-28                    United Airlines       826
16 1998-02-02                       Cebu Pacific       387
17 1998-02-16                     China Airlines       676
18 1998-03-22                Philippine Airlines       137
19 1998-04-20                         Air France       422
20 1998-05-25                                PIA       544
21 1998-06-18                            Propair       420
22 1998-07-30                   Proteus Airlines       706
23 1998-08-24                     Myanma Airways       635
24 1998-08-29                 Cubana de Aviación       389
25 1998-09-02                           Swissair       111
26 1998-09-25                           PauknAir      4101
27 1998-09-29                            Lionair       602
28 1998-12-11         Thai Airways International       261
29 1999-02-24           China Southwest Airlines      4509
..        ...                                ...       ...
70 2001-08-24                        Air Transat       236
71 2001-08-29                Binter Mediterráneo      8261
72 2001-09-11                  American Airlines        11
73 2001-09-11                    United Airlines       175
74 2001-09-11                  American Airlines        77
75 2001-09-11                    United Airlines        93
76 2001-10-04                   Siberia Airlines      1812
77 2001-10-08              Scandinavian Airlines       686
78 2001-11-12                  American Airlines       587
79 2001-11-24                           Crossair      3597
80 2001-12-22         On board American Airlines        63
81 2002-01-14                           Lion Air       386
82 2002-01-16                   Garuda Indonesia       421
83 2002-01-28                               TAME       120
84 2002-02-12                     Iran Air Tours       956
85 2002-04-15                          Air China       129
86 2002-05-04                       EAS Airlines      4226
87 2002-05-07                           EgyptAir       843
88 2002-05-07            China Northern Airlines      6136
89 2002-05-25                     China Airlines       611
90 2002-07-01                Bashkirian Airlines      2937
91 2002-07-10       Swiss International Airlines       850
92 2002-08-30                 Rico Linhas Aéreas      4823
93 2002-10-09                 Northwest Airlines        85
94 2002-11-06                             Luxair      9642
95 2002-11-11       Laoag International Airlines       585
96 2003-01-08                        Air Midwest      5481
97 2003-01-08                   Turkish Airlines       634
98 2003-01-09                          TANS Perú       222
99 2003-03-06                        Air Algérie      6289

[100 rows x 3 columns]

## Step 2

In [132]:
airports_df.head()

,airport_id,airport_name,city,airport_county,faa,airport_icao,lat,lon,alt,timezone,dst,tz
0,1,Goroka,Goroka,Papua New Guinea,GKA,AYGA,-6.081689,145.391881,5282,10.0,U,Pacific/Port_Moresby
1,2,Madang,Madang,Papua New Guinea,MAG,AYMD,-5.207083,145.788700,20,10.0,U,Pacific/Port_Moresby
2,3,Mount Hagen,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826789,144.295861,5388,10.0,U,Pacific/Port_Moresby
3,4,Nadzab,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569828,146.726242,239,10.0,U,Pacific/Port_Moresby
4,5,Port Moresby Jacksons Intl,Port Moresby,Papua New Guinea,POM,AYPY,-9.443383,147.220050,146,10.0,U,Pacific/Port_Moresby

In [133]:
airlines_df.head()

,airline_id,airline_name,alias,iata,airline_icao,callsign,airline_county,airline_Y
0,1,Private flight,,-,,,,Y
1,2,135 Airways,,,GNL,GENERAL,United States,N
2,3,1Time Airline,,1T,RNX,NEXTIME,South Africa,Y
3,4,2 Sqn No 1 Elementary Flying Training School,,,WYT,,United Kingdom,N
4,5,213 Flight Unit,,,TFU,,Russia,N

In [134]:
routes_df.head()

,airline_iata_icao,r_airline_id,source_airport_iata_icao,source_airport_id,destin_airport_iata_icao,destin_airport_id,Y,stops,equipment
0,2B,410,AER,2965,KZN,2990,,0,CR2
1,2B,410,ASF,2966,KZN,2990,,0,CR2
2,2B,410,ASF,2966,MRV,2962,,0,CR2
3,2B,410,CEK,2968,KZN,2990,,0,CR2
4,2B,410,CEK,2968,OVB,4078,,0,CR2

In [135]:
incidents_df.head()

        Date                            Airline FlightNum
0 1997-01-09                             Comair      3272
1 1997-03-18  Stavropolskaya Aktsionernaya Avia      1023
2 1997-04-19         Merpati Nusantara Airlines       106
3 1997-05-08            China Southern Airlines      3456
4 1997-07-31                      FedEx Express        14

## Tasks for Step 3

In [136]:
# TODO: add the SQLite3 starter code from Step 3
import sqlite3
engine = sqlite3.connect('HW1_DB')
# Use to_sql to save your Dataframes
incidents_df.to_sql(name = 'incidents', 
                    con = engine, 
                    index=False,
                    if_exists='replace')
airlines_df.to_sql(name = 'airlines', 
                    con = engine, 
                    index=False,
                    if_exists='replace')
airports_df.to_sql(name = 'airports', 
                    con = engine, 
                    index=False,
                    if_exists='replace')
flights_df.to_sql(name = 'flights', 
                    con = engine, 
                    index=False,
                    if_exists='replace')
routes_df.to_sql(name = 'routes', 
                    con = engine, 
                    index=False,
                    if_exists='replace')

In [137]:
# Test that the data is there!

cursor = engine.execute('select * from airports limit 1000')
rows = cursor.fetchall()
rows

[(1,
  'Goroka',
  'Goroka',
  'Papua New Guinea',
  'GKA',
  'AYGA',
  -6.081689,
  145.391881,
  5282,
  10.0,
  'U',
  'Pacific/Port_Moresby'),
 (2,
  'Madang',
  'Madang',
  'Papua New Guinea',
  'MAG',
  'AYMD',
  -5.207083,
  145.7887,
  20,
  10.0,
  'U',
  'Pacific/Port_Moresby'),
 (3,
  'Mount Hagen',
  'Mount Hagen',
  'Papua New Guinea',
  'HGU',
  'AYMH',
  -5.826789,
  144.295861,
  5388,
  10.0,
  'U',
  'Pacific/Port_Moresby'),
 (4,
  'Nadzab',
  'Nadzab',
  'Papua New Guinea',
  'LAE',
  'AYNZ',
  -6.569828,
  146.72624199999998,
  239,
  10.0,
  'U',
  'Pacific/Port_Moresby'),
 (5,
  'Port Moresby Jacksons Intl',
  'Port Moresby',
  'Papua New Guinea',
  'POM',
  'AYPY',
  -9.443383,
  147.22005,
  146,
  10.0,
  'U',
  'Pacific/Port_Moresby'),
 (6,
  'Wewak Intl',
  'Wewak',
  'Papua New Guinea',
  'WWK',
  'AYWK',
  -3.583828,
  143.669186,
  19,
  10.0,
  'U',
  'Pacific/Port_Moresby'),
 (7,
  'Narsarsuaq',
  'Narssarssuaq',
  'Greenland',
  'UAK',
  'BGBW',
  61.160517000000006,
  -45.425978,
  112,
  -3.0,
  'E',
  'America/Godthab'),
 (8,
  'Nuuk',
  'Godthaab',
  'Greenland',
  'GOH',
  'BGGH',
  64.190922,
  -51.678064,
  283,
  -3.0,
  'E',
  'America/Godthab'),
 (9,
  'Sondre Stromfjord',
  'Sondrestrom',
  'Greenland',
  'SFJ',
  'BGSF',
  67.01696899999999,
  -50.689325,
  165,
  -3.0,
  'E',
  'America/Godthab'),
 (10,
  'Thule Air Base',
  'Thule',
  'Greenland',
  'THU',
  'BGTL',
  76.531203,
  -68.703161,
  251,
  -4.0,
  'E',
  'America/Thule'),
 (11,
  'Akureyri',
  'Akureyri',
  'Iceland',
  'AEY',
  'BIAR',
  65.659994,
  -18.072703,
  6,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (12,
  'Egilsstadir',
  'Egilsstadir',
  'Iceland',
  'EGS',
  'BIEG',
  65.283333,
  -14.401389000000002,
  76,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (13,
  'Hornafjordur',
  'Hofn',
  'Iceland',
  'HFN',
  'BIHN',
  64.295556,
  -15.227222,
  24,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (14,
  'Husavik',
  'Husavik',
  'Iceland',
  'HZK',
  'BIHU',
  65.95232800000001,
  -17.425978,
  48,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (15,
  'Isafjordur',
  'Isafjordur',
  'Iceland',
  'IFJ',
  'BIIS',
  66.05805600000001,
  -23.135278,
  8,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (16,
  'Keflavik International Airport',
  'Keflavik',
  'Iceland',
  'KEF',
  'BIKF',
  63.985,
  -22.605556,
  171,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (17,
  'Patreksfjordur',
  'Patreksfjordur',
  'Iceland',
  'PFJ',
  'BIPA',
  65.55583299999999,
  -23.965,
  11,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (18,
  'Reykjavik',
  'Reykjavik',
  'Iceland',
  'RKV',
  'BIRK',
  64.13,
  -21.940556,
  48,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (19,
  'Siglufjordur',
  'Siglufjordur',
  'Iceland',
  'SIJ',
  'BISI',
  66.133333,
  -18.916667,
  10,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (20,
  'Vestmannaeyjar',
  'Vestmannaeyjar',
  'Iceland',
  'VEY',
  'BIVM',
  63.424303,
  -20.278875,
  326,
  0.0,
  'N',
  'Atlantic/Reykjavik'),
 (21,
  'Sault Ste Marie',
  'Sault Sainte Marie',
  'Canada',
  'YAM',
  'CYAM',
  46.485001000000004,
  -84.509445,
  630,
  -5.0,
  'A',
  'America/Toronto'),
 (22,
  'Winnipeg St Andrews',
  'Winnipeg',
  'Canada',
  'YAV',
  'CYAV',
  50.056389,
  -97.0325,
  760,
  -6.0,
  'A',
  'America/Winnipeg'),
 (23,
  'Shearwater',
  'Halifax',
  'Canada',
  'YAW',
  'CYAW',
  44.639721,
  -63.499444,
  167,
  -4.0,
  'A',
  'America/Halifax'),
 (24,
  'St Anthony',
  'St. Anthony',
  'Canada',
  'YAY',
  'CYAY',
  51.391944,
  -56.083056000000006,
  108,
  -3.5,
  'A',
  'America/St_Johns'),
 (25,
  'Tofino',
  'Tofino',
  'Canada',
  'YAZ',
  'CYAZ',
  49.082221999999994,
  -125.7725,
  80,
  -8.0,
  'A',
  'America/Vancouver'),
 (26,
  'Kugaaruk',
  'Pelly Bay',
  'Canada',
  'YBB',
  'CYBB',
  68.534444,
  -89.80805600000001,
  56,
  -7.0,
  'A',
  'America/Edmonton'),
 (27,
  'Baie Comeau',
  'Baie Comeau',
  'Canada',
  'YBC',
  'CYBC',
  49.1325,
  -68.204444,
  71,
  -5.0,
  'A',
  'America/Toronto'),
 (28,
  'Bagotville',
  'Bagotville',
  'Canada',
  'YBG',
  'CYBG',
  48.330555,
  -70.996391,
  522,
  -5.0,
  'A',
  'America/Toronto'),
 (29,
  'Baker Lake',
  'Baker Lake',
  'Canada',
  'YBK',
  'CYBK',
  64.298889,
  -96.07777800000001,
  59,
  -6.0,
  'A',
  'America/Winnipeg'),
 (30,
  'Campbell River',
  'Campbell River',
  'Canada',
  'YBL',
  'CYBL',
  49.950832,
  -125.27083300000001,
  346,
  -8.0,
  'A',
  'America/Vancouver'),
 (31,
  'Brandon Muni',
  'Brandon',
  'Canada',
  'YBR',
  'CYBR',
  49.91,
  -99.951944,
  1343,
  -6.0,
  'A',
  'America/Winnipeg'),
 (32,
  'Cambridge Bay',
  'Cambridge Bay',
  'Canada',
  'YCB',
  'CYCB',
  69.10805500000001,
  -105.138333,
  90,
  -7.0,
  'A',
  'America/Edmonton'),
 (33,
  'Nanaimo',
  'Nanaimo',
  'Canada',
  'YCD',
  'CYCD',
  49.052333000000004,
  -123.870167,
  93,
  -8.0,
  'A',
  'America/Vancouver'),
 (34,
  'Castlegar',
  'Castlegar',
  'Canada',
  'YCG',
  'CYCG',
  49.296389000000005,
  -117.6325,
  1624,
  -8.0,
  'A',
  'America/Vancouver'),
 (35,
  'Miramichi',
  'Chatham',
  'Canada',
  'YCH',
  'CYCH',
  47.007778,
  -65.449167,
  108,
  -4.0,
  'A',
  'America/Halifax'),
 (36,
  'Charlo',
  'Charlo',
  'Canada',
  'YCL',
  'CYCL',
  47.990833,
  -66.330278,
  132,
  -4.0,
  'A',
  'America/Halifax'),
 (37,
  'Kugluktuk',
  'Coppermine',
  'Canada',
  'YCO',
  'CYCO',
  67.81666700000001,
  -115.14388899999999,
  74,
  -7.0,
  'A',
  'America/Edmonton'),
 (38,
  'Coronation',
  'Coronation',
  'Canada',
  'YCT',
  'CYCT',
  52.075001,
  -111.445278,
  2595,
  -7.0,
  'A',
  'America/Edmonton'),
 (39,
  'Chilliwack',
  'Chilliwack',
  'Canada',
  'YCW',
  'CYCW',
  49.152778999999995,
  -121.93888999999999,
  32,
  -8.0,
  'A',
  'America/Vancouver'),
 (40,
  'Clyde River',
  'Clyde River',
  'Canada',
  'YCY',
  'CYCY',
  70.486111,
  -68.516667,
  87,
  -5.0,
  'A',
  'America/Toronto'),
 (41,
  'Fairmont Hot Springs',
  'Coral Harbour',
  'Canada',
  'YZS',
  'CYCZ',
  64.193333,
  -83.359444,
  2661,
  -5.0,
  'A',
  'America/Coral_Harbour'),
 (42,
  'Dawson City',
  'Dawson',
  'Canada',
  'YDA',
  'CYDA',
  64.043056,
  -139.127778,
  1215,
  -8.0,
  'A',
  'America/Vancouver'),
 (43,
  'Burwash',
  'Burwash',
  'Canada',
  'YDB',
  'CYDB',
  61.371111,
  -139.040556,
  2647,
  -8.0,
  'A',
  'America/Vancouver'),
 (44,
  'Princeton',
  'Princeton',
  'Canada',
  'YDC',
  'CYDC',
  49.468056,
  -120.511389,
  2298,
  -8.0,
  'A',
  'America/Vancouver'),
 (45,
  'Deer Lake',
  'Deer Lake',
  'Canada',
  'YDF',
  'CYDF',
  49.210833,
  -57.391388,
  72,
  -3.5,
  'A',
  'America/St_Johns'),
 (46,
  'Dease Lake',
  'Dease Lake',
  'Canada',
  'YDL',
  'CYDL',
  58.422222,
  -130.032222,
  2600,
  -8.0,
  'A',
  'America/Vancouver'),
 (47,
  'Dauphin Barker',
  'Dauphin',
  'Canada',
  'YDN',
  'CYDN',
  51.100834000000006,
  -100.0525,
  999,
  -6.0,
  'A',
  'America/Winnipeg'),
 (48,
  'Dawson Creek',
  'Dawson Creek',
  'Canada',
  'YDQ',
  'CYDQ',
  55.742332999999995,
  -120.18299999999999,
  2148,
  -7.0,
  'A',
  'America/Dawson_Creek'),
 (49,
  'Edmonton Intl',
  'Edmonton',
  'Canada',
  'YEG',
  'CYEG',
  53.309723,
  -113.579722,
  2373,
  -7.0,
  'A',
  'America/Edmonton'),
 (50,
  'Arviat',
  'Eskimo Point',
  'Canada',
  'YEK',
  'CYEK',
  61.094166,
  -94.070833,
  32,
  -6.0,
  'A',
  'America/Winnipeg'),
 (51,
  'Estevan',
  'Estevan',
  'Canada',
  'YEN',
  'CYEN',
  49.210278,
  -102.96583299999999,
  1905,
  -6.0,
  'N',
  'America/Regina'),
 (52,
  'Edson',
  'Edson',
  'Canada',
  'YET',
  'CYET',
  53.578888,
  -116.465,
  3041,
  -7.0,
  'A',
  'America/Edmonton'),
 (53,
  'Eureka',
  'Eureka',
  'Canada',
  'YEU',
  'CYEU',
  79.994722,
  -85.814167,
  256,
  -6.0,
  'A',
  'America/Winnipeg'),
 (54,
  'Inuvik Mike Zubko',
  'Inuvik',
  'Canada',
  'YEV',
  'CYEV',
  68.304167,
  -133.482778,
  224,
  -7.0,
  'A',
  'America/Edmonton'),
 (55,
  'Iqaluit',
  'Iqaluit',
  'Canada',
  'YFB',
  'CYFB',
  63.75639,
  -68.555832,
  110,
  -5.0,
  'A',
  'America/Toronto'),
 (56,
  'Fredericton',
  'Fredericton',
  'Canada',
  'YFC',
  'CYFC',
  45.868889,
  -66.537222,
  68,
  -4.0,
  'A',
  'America/Halifax'),
 (57,
  'Forestville',
  'Forestville',
  'Canada',
  '',
  'CYFE',
  48.746111,
  -69.097222,
  293,
  -5.0,
  'A',
  'America/Toronto'),
 (58,
  'Flin Flon',
  'Flin Flon',
  'Canada',
  'YFO',
  'CYFO',
  54.67805500000001,
  -101.681667,
  997,
  -6.0,
  'A',
  'America/Winnipeg'),
 (59,
  'Fort Resolution',
  'Fort Resolution',
  'Canada',
  'YFR',
  'CYFR',
  61.180831999999995,
  -113.689722,
  526,
  -7.0,
  'A',
  'America/Edmonton'),
 (60,
  'Fort Simpson',
  'Fort Simpson',
  'Canada',
  'YFS',
  'CYFS',
  61.760153,
  -121.236525,
  555,
  -7.0,
  'A',
  'America/Edmonton'),
 (61,
  'Kingston',
  'Kingston',
  'Canada',
  'YGK',
  'CYGK',
  44.225277,
  -76.596944,
  305,
  -5.0,
  'A',
  'America/Toronto'),
 (62,
  'La Grande Riviere',
  'La Grande Riviere',
  'Canada',
  'YGL',
  'CYGL',
  53.625278,
  -77.704167,
  639,
  -5.0,
  'A',
  'America/Toronto'),
 (63,
  'Gaspe',
  'Gaspe',
  'Canada',
  'YGP',
  'CYGP',
  48.775278,
  -64.478611,
  108,
  -5.0,
  'A',
  'America/Toronto'),
 (64,
  'Geraldton Greenstone Regional',
  'Geraldton',
  'Canada',
  'YGQ',
  'CYGQ',
  49.778332,
  -86.93944499999999,
  1144,
  -5.0,
  'A',
  'America/Toronto'),
 (65,
  'Iles De La Madeleine',
  'Iles De La Madeleine',
  'Canada',
  'YGR',
  'CYGR',
  47.424721000000005,
  -61.77805600000001,
  35,
  -5.0,
  'A',
  'America/Toronto'),
 (66,
  'Hudson Bay',
  'Hudson Bay',
  'Canada',
  'YHB',
  'CYHB',
  52.816666000000005,
  -102.31139,
  1175,
  -6.0,
  'N',
  'America/Regina'),
 (67,
  'Dryden Rgnl',
  'Dryden',
  'Canada',
  'YHD',
  'CYHD',
  49.831666999999996,
  -92.744167,
  1354,
  -6.0,
  'A',
  'America/Winnipeg'),
 (68,
  'Ulukhaktok Holman',
  'Holman Island',
  'Canada',
  'YHI',
  'CYHI',
  70.762778,
  -117.80611100000002,
  117,
  -7.0,
  'A',
  'America/Edmonton'),
 (69,
  'Gjoa Haven',
  'Gjoa Haven',
  'Canada',
  'YHK',
  'CYHK',
  68.63555600000001,
  -95.849722,
  152,
  -7.0,
  'A',
  'America/Edmonton'),
 (70,
  'Hamilton',
  'Hamilton',
  'Canada',
  'YHM',
  'CYHM',
  43.173611,
  -79.935,
  780,
  -5.0,
  'A',
  'America/Toronto'),
 (71,
  'St Hubert',
  'Montreal',
  'Canada',
  'YHU',
  'CYHU',
  45.5175,
  -73.416944,
  90,
  -5.0,
  'A',
  'America/Toronto'),
 (72,
  'Hay River',
  'Hay River',
  'Canada',
  'YHY',
  'CYHY',
  60.839721999999995,
  -115.78277800000001,
  543,
  -7.0,
  'A',
  'America/Edmonton'),
 (73,
  'Halifax Intl',
  'Halifax',
  'Canada',
  'YHZ',
  'CYHZ',
  44.880833,
  -63.50861,
  477,
  -4.0,
  'A',
  'America/Halifax'),
 (74,
  'Atikokan Muni',
  'Atikokan',
  'Canada',
  'YIB',
  'CYIB',
  48.773888,
  -91.638611,
  1408,
  -5.0,
  'A',
  'America/Coral_Harbour'),
 (75,
  'Pond Inlet',
  'Pond Inlet',
  'Canada',
  'YIO',
  'CYIO',
  72.683334,
  -77.966667,
  181,
  -5.0,
  'A',
  'America/Toronto'),
 (76,
  'St Jean',
  'St. Jean',
  'Canada',
  'YJN',
  'CYJN',
  45.294445,
  -73.281111,
  136,
  -5.0,
  'A',
  'America/Toronto'),
 (77,
  'Stephenville',
  'Stephenville',
  'Canada',
  'YJT',
  'CYJT',
  48.544167,
  -58.549999,
  80,
  -3.5,
  'A',
  'America/St_Johns'),
 (78,
  'Kamloops',
  'Kamloops',
  'Canada',
  'YKA',
  'CYKA',
  50.702222,
  -120.44444399999999,
  1133,
  -8.0,
  'A',
  'America/Vancouver'),
 (79,
  'Waterloo',
  'Waterloo',
  'Canada',
  'YKF',
  'CYKF',
  43.460833,
  -80.37861099999999,
  1054,
  -5.0,
  'A',
  'America/Toronto'),
 (80,
  'Schefferville',
  'Schefferville',
  'Canada',
  'YKL',
  'CYKL',
  54.805278,
  -66.805278,
  1709,
  -5.0,
  'A',
  'America/Toronto'),
 (81,
  'Kindersley',
  'Kindersley',
  'Canada',
  'YKY',
  'CYKY',
  51.5175,
  -109.180833,
  2277,
  -6.0,
  'N',
  'America/Regina'),
 (82,
  'Buttonville Muni',
  'Toronto',
  'Canada',
  'YKZ',
  'CYKZ',
  43.862221000000005,
  -79.37,
  650,
  -5.0,
  'A',
  'America/Toronto'),
 (83,
  'Chapleau',
  'Chapleau',
  'Canada',
  'YLD',
  'CYLD',
  47.82,
  -83.34666700000001,
  1470,
  -5.0,
  'A',
  'America/Toronto'),
 (84,
  'Meadow Lake',
  'Meadow Lake',
  'Canada',
  'YLJ',
  'CYLJ',
  54.125278,
  -108.522778,
  1576,
  -6.0,
  'N',
  'America/Regina'),
 (85,
  'Lloydminster',
  'Lloydminster',
  'Canada',
  'YLL',
  'CYLL',
  53.309166000000005,
  -110.0725,
  2193,
  -7.0,
  'A',
  'America/Edmonton'),
 (86,
  'Alert',
  'Alert',
  'Canada',
  'YLT',
  'CYLT',
  82.517778,
  -62.280556000000004,
  100,
  -5.0,
  'A',
  'America/Toronto'),
 (87,
  'Kelowna',
  'Kelowna',
  'Canada',
  'YLW',
  'CYLW',
  49.956112,
  -119.377778,
  1409,
  -8.0,
  'A',
  'America/Vancouver'),
 (88,
  'Mayo',
  'Mayo',
  'Canada',
  'YMA',
  'CYMA',
  63.616389,
  -135.868333,
  1653,
  -8.0,
  'A',
  'America/Vancouver'),
 (89,
  'Moose Jaw Air Vice Marshal C M Mcewen',
  'Moose Jaw',
  'Canada',
  'YMJ',
  'CYMJ',
  50.330278,
  -105.55916699999999,
  1892,
  -6.0,
  'N',
  'America/Regina'),
 (90,
  'Fort Mcmurray',
  'Fort Mcmurray',
  'Canada',
  'YMM',
  'CYMM',
  56.653332999999996,
  -111.221944,
  1211,
  -7.0,
  'A',
  'America/Edmonton'),
 (91,
  'Moosonee',
  'Moosonee',
  'Canada',
  'YMO',
  'CYMO',
  51.291111,
  -80.607778,
  30,
  -5.0,
  'A',
  'America/Toronto'),
 (92,
  'Maniwaki',
  'Maniwaki',
  'Canada',
  'YMW',
  'CYMW',
  46.272778,
  -75.99055600000001,
  656,
  -5.0,
  'A',
  'America/Toronto'),
 (93,
  'Montreal Intl Mirabel',
  'Montreal',
  'Canada',
  'YMX',
  'CYMX',
  45.681944,
  -74.005278,
  270,
  -5.0,
  'A',
  'America/Toronto'),
 (94,
  'Natashquan',
  'Natashquan',
  'Canada',
  'YNA',
  'CYNA',
  50.19,
  -61.789167000000006,
  39,
  -5.0,
  'A',
  'America/Toronto'),
 (95,
  'Gatineau',
  'Gatineau',
  'Canada',
  'YND',
  'CYND',
  45.521694000000004,
  -75.56358900000001,
  211,
  -5.0,
  'A',
  'America/Toronto'),
 (96,
  'Matagami',
  'Matagami',
  'Canada',
  'YNM',
  'CYNM',
  49.761666999999996,
  -77.802778,
  918,
  -5.0,
  'A',
  'America/Toronto'),
 (97,
  'Old Crow',
  'Old Crow',
  'Canada',
  'YOC',
  'CYOC',
  67.57055600000001,
  -139.839167,
  824,
  -8.0,
  'A',
  'America/Vancouver'),
 (98,
  'Cold Lake',
  'Cold Lake',
  'Canada',
  'YOD',
  'CYOD',
  54.404999,
  -110.279444,
  1775,
  -7.0,
  'A',
  'America/Edmonton'),
 (99,
  'High Level',
  'High Level',
  'Canada',
  'YOJ',
  'CYOJ',
  58.621389,
  -117.164722,
  1110,
  -7.0,
  'A',
  'America/Edmonton'),
 (100,
  'Ottawa Macdonald Cartier Intl',
  'Ottawa',
  'Canada',
  'YOW',
  'CYOW',
  45.3225,
  -75.669167,
  374,
  -5.0,
  'A',
  'America/Toronto'),
 (101,
  'Prince Albert Glass Field',
  'Prince Albert',
  'Canada',
  'YPA',
  'CYPA',
  53.214167,
  -105.67277800000001,
  1405,
  -6.0,
  'N',
  'America/Regina'),
 (102,
  'Peace River',
  'Peace River',
  'Canada',
  'YPE',
  'CYPE',
  56.226943999999996,
  -117.447222,
  1873,
  -7.0,
  'A',
  'America/Edmonton'),
 (103,
  'Southport',
  'Portage-la-prairie',
  'Canada',
  'YPG',
  'CYPG',
  49.903056,
  -98.273889,
  885,
  -6.0,
  'A',
  'America/Winnipeg'),
 (104,
  'Pitt Meadows',
  'Pitt Meadows',
  'Canada',
  '',
  'CYPK',
  49.21611,
  -122.71,
  11,
  -8.0,
  'A',
  'America/Vancouver'),
 (105,
  'Pickle Lake',
  'Pickle Lake',
  'Canada',
  'YPL',
  'CYPL',
  51.446388,
  -90.214167,
  1267,
  -5.0,
  'A',
  'America/Coral_Harbour'),
 (106,
  'Port Menier',
  'Port Menier',
  'Canada',
  'YPN',
  'CYPN',
  49.836389000000004,
  -64.288611,
  167,
  -5.0,
  'A',
  'America/Toronto'),
 (107,
  'Peterborough',
  'Peterborough',
  'Canada',
  'YPQ',
  'CYPQ',
  44.23,
  -78.363333,
  628,
  -5.0,
  'A',
  'America/Toronto'),
 (108,
  'Prince Rupert',
  'Prince Pupert',
  'Canada',
  'YPR',
  'CYPR',
  54.28611,
  -130.44472199999998,
  116,
  -8.0,
  'A',
  'America/Vancouver'),
 (109,
  'Fort Chipewyan',
  'Fort Chipewyan',
  'Canada',
  'YPY',
  'CYPY',
  58.767223,
  -111.117222,
  761,
  -7.0,
  'A',
  'America/Edmonton'),
 (110,
  'Muskoka',
  'Muskoka',
  'Canada',
  'YQA',
  'CYQA',
  44.974722,
  -79.303333,
  925,
  -5.0,
  'A',
  'America/Toronto'),
 (111,
  'Quebec Jean Lesage Intl',
  'Quebec',
  'Canada',
  'YQB',
  'CYQB',
  46.791111,
  -71.393333,
  244,
  -5.0,
  'A',
  'America/Toronto'),
 (112,
  'Red Deer Regional',
  'Red Deer Industrial',
  'Canada',
  'YQF',
  'CYQF',
  52.182221999999996,
  -113.894444,
  2968,
  -7.0,
  'A',
  'America/Edmonton'),
 (113,
  'Windsor',
  'Windsor',
  'Canada',
  'YQG',
  'CYQG',
  42.275556,
  -82.955556,
  622,
  -5.0,
  'A',
  'America/Toronto'),
 (114,
  'Watson Lake',
  'Watson Lake',
  'Canada',
  'YQH',
  'CYQH',
  60.116389,
  -128.8225,
  2255,
  -8.0,
  'A',
  'America/Vancouver'),
 (115,
  'Kenora',
  'Kenora',
  'Canada',
  'YQK',
  'CYQK',
  49.788334000000006,
  -94.363056,
  1332,
  -6.0,
  'A',
  'America/Winnipeg'),
 (116,
  'Lethbridge',
  'Lethbridge',
  'Canada',
  'YQL',
  'CYQL',
  49.630278000000004,
  -112.799722,
  3047,
  -7.0,
  'A',
  'America/Edmonton'),
 (117,
  'Greater Moncton Intl',
  'Moncton',
  'Canada',
  'YQM',
  'CYQM',
  46.112221000000005,
  -64.678611,
  232,
  -4.0,
  'A',
  'America/Halifax'),
 (119,
  'Comox',
  'Comox',
  'Canada',
  'YQQ',
  'CYQQ',
  49.710833,
  -124.88666699999999,
  84,
  -8.0,
  'A',
  'America/Vancouver'),
 (120,
  'Regina Intl',
  'Regina',
  'Canada',
  'YQR',
  'CYQR',
  50.431944,
  -104.66583299999999,
  1894,
  -6.0,
  'N',
  'America/Regina'),
 (121,
  'Thunder Bay',
  'Thunder Bay',
  'Canada',
  'YQT',
  'CYQT',
  48.371944,
  -89.32388900000001,
  653,
  -5.0,
  'A',
  'America/Toronto'),
 (122,
  'Grande Prairie',
  'Grande Prairie',
  'Canada',
  'YQU',
  'CYQU',
  55.179722,
  -118.885,
  2195,
  -7.0,
  'A',
  'America/Edmonton'),
 (123,
  'Yorkton Muni',
  'Yorkton',
  'Canada',
  'YQV',
  'CYQV',
  51.264721,
  -102.461667,
  1635,
  -6.0,
  'N',
  'America/Regina'),
 (124,
  'North Battleford',
  'North Battleford',
  'Canada',
  'YQW',
  'CYQW',
  52.769167,
  -108.24361,
  1799,
  -6.0,
  'N',
  'America/Regina'),
 (125,
  'Gander Intl',
  'Gander',
  'Canada',
  'YQX',
  'CYQX',
  48.936944,
  -54.568056000000006,
  496,
  -3.5,
  'A',
  'America/St_Johns'),
 (126,
  'Sydney',
  'Sydney',
  'Canada',
  'YQY',
  'CYQY',
  46.161388,
  -60.047779000000006,
  203,
  -4.0,
  'A',
  'America/Halifax'),
 (127,
  'Quesnel',
  'Quesnel',
  'Canada',
  'YQZ',
  'CYQZ',
  53.026112,
  -122.510278,
  1789,
  -8.0,
  'A',
  'America/Vancouver'),
 (128,
  'Resolute Bay',
  'Resolute',
  'Canada',
  'YRB',
  'CYRB',
  74.716944,
  -94.969444,
  215,
  -6.0,
  'A',
  'America/Winnipeg'),
 (129,
  'Riviere Du Loup',
  'Riviere Du Loup',
  'Canada',
  'YRI',
  'CYRI',
  47.764444,
  -69.584722,
  427,
  -5.0,
  'A',
  'America/Toronto'),
 (130,
  'Roberval',
  'Roberval',
  'Canada',
  'YRJ',
  'CYRJ',
  48.52,
  -72.265556,
  586,
  -5.0,
  'A',
  'America/Toronto'),
 (131,
  'Rocky Mountain House',
  'Rocky Mountain House',
  'Canada',
  'YRM',
  'CYRM',
  52.429722,
  -114.90416699999999,
  3244,
  -7.0,
  'A',
  'America/Edmonton'),
 (132,
  'Rankin Inlet',
  'Rankin Inlet',
  'Canada',
  'YRT',
  'CYRT',
  62.81139,
  -92.115833,
  94,
  -6.0,
  'A',
  'America/Winnipeg'),
 (133,
  'Sudbury',
  'Sudbury',
  'Canada',
  'YSB',
  'CYSB',
  46.625,
  -80.798889,
  1141,
  -5.0,
  'A',
  'America/Toronto'),
 (134,
  'Sherbrooke',
  'Sherbrooke',
  'Canada',
  'YSC',
  'CYSC',
  45.438611,
  -71.691389,
  792,
  -5.0,
  'A',
  'America/Toronto'),
 (135,
  'Saint John',
  'St. John',
  'Canada',
  'YSJ',
  'CYSJ',
  45.316111,
  -65.89027800000001,
  357,
  -4.0,
  'A',
  'America/Halifax'),
 (136,
  'Fort Smith',
  'Fort Smith',
  'Canada',
  'YSM',
  'CYSM',
  60.020278000000005,
  -111.96194399999999,
  671,
  -7.0,
  'A',
  'America/Edmonton'),
 (137,
  'Nanisivik',
  'Nanisivik',
  'Canada',
  'YSR',
  'CYSR',
  72.982222,
  -84.61361099999999,
  2106,
  -5.0,
  'A',
  'America/Toronto'),
 (138,
  'Summerside',